version: '3'
services:
  web: #This is flask server container
    container_name: flask_api_server
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on: 
      - db
    networks: 
      - mynet
    ports:
      - "5000:5000"
    volumes:
      - /Users/anh/Desktop/containerized-app/server:/flask
    env_file: 
      - .env

  db: #This is postgres database container
    image: postgres
    volumes:
      - ./mydata/postgres:/var/lib/postgresql/data
    networks: 
      - mynet
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks: 
  mynet:

volumes:
  mydata: 