version: '3.3'
services:
  web_service:
    container_name: flask_server
    restart: always
    build: .
    depends_on: 
      - db_service
    ports:
      - "8000:5000"
    volumes:
      - /Users/anh/Desktop/containerized-app/server
    environment:
      - 
  db_service:
    image: postgres:latest
    restart: always
    