version: 2
jobs:
  build:
    docker:
      - image: 278749303080.dkr.ecr.us-east-1.amazonaws.com/flask-postgresdb-docker:latest

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date